version: "3.8"
services:
  nodeapp:
    build: .
    working_dir: /app
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres.afcdpuxclefvznfztqdf
      - DB_PASSWORD=
      - DB_HOST=aws-0-eu-central-1.pooler.supabase.com
      - DB_PORT=5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
